"""Pydantic schemas package."""

from app.schemas.user import UserRegister, UserLogin, UserResponse, TokenResponse
from app.schemas.course import (
    CourseCreate,
    CourseUpdate,
    CourseResponse,
    CourseDetailResponse,
    TopicCreate,
    TopicResponse,
)
from app.schemas.document import (
    DocumentResponse,
    DocumentDetailResponse,
    DocumentChunkResponse,
)
from app.schemas.rag import (
    RAGQueryRequest,
    SourceCitation,
    RAGResponse,
    RAGIndexStatusResponse,
)
from app.schemas.tutor import (
    VALID_PEDAGOGICAL_MODES,
    TutorSessionCreate,
    TutorSessionUpdateMode,
    TutorMessageCreate,
    TutorMessageResponse,
    TutorSessionResponse,
    TutorSessionDetailResponse,
)
from app.schemas.assessment import (
    BloomLevel,
    QuestionType,
    AssessmentDifficulty,
    QuestionOption,
    QuestionOptionStudent,
    QuestionCreate,
    QuestionResponse,
    QuestionStudentView,
    AssessmentCreate,
    AssessmentGenerateRequest,
    AssessmentResponse,
    AssessmentDetailResponse,
    AssessmentStudentDetailResponse,
    AssessmentSubmitRequest,
    QuestionResultResponse,
    AssessmentAttemptResponse,
    AssessmentAttemptDetailResponse,
)

__all__ = [
    "UserRegister",
    "UserLogin",
    "UserResponse",
    "TokenResponse",
    "CourseCreate",
    "CourseUpdate",
    "CourseResponse",
    "CourseDetailResponse",
    "TopicCreate",
    "TopicResponse",
    "DocumentResponse",
    "DocumentDetailResponse",
    "DocumentChunkResponse",
    "RAGQueryRequest",
    "SourceCitation",
    "RAGResponse",
    "RAGIndexStatusResponse",
    "VALID_PEDAGOGICAL_MODES",
    "TutorSessionCreate",
    "TutorSessionUpdateMode",
    "TutorMessageCreate",
    "TutorMessageResponse",
    "TutorSessionResponse",
    "TutorSessionDetailResponse",
    "BloomLevel",
    "QuestionType",
    "AssessmentDifficulty",
    "QuestionOption",
    "QuestionOptionStudent",
    "QuestionCreate",
    "QuestionResponse",
    "QuestionStudentView",
    "AssessmentCreate",
    "AssessmentGenerateRequest",
    "AssessmentResponse",
    "AssessmentDetailResponse",
    "AssessmentStudentDetailResponse",
    "AssessmentSubmitRequest",
    "QuestionResultResponse",
    "AssessmentAttemptResponse",
    "AssessmentAttemptDetailResponse",
]
